[package]
name = "polynomial_ops"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Multivariable polynomial operations on arrays and vectors"
repository = "https://github.com/sigurd4/polynomial_ops"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_identities_const = "0.1.0"
option_trait = "0.1.3"
currying = "0.2.1"
moddef = "0.2.2"
num = "0.4.1"
array_trait = "0.6.15"
sized_const = "0.1.0"

[dev-dependencies]
plotters = "0.3.5"
linspace = "0.1.0"

[features]
default = ["std"]
std = []